"use client";
import { useState } from "react";
import { api } from "@/lib/api";

export default function QuestionGenerationPage() {
  const [resourceId,setResourceId]=useState("");const [job,setJob]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const generate=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(`/api/resources/${resourceId}/generate-mcqs`,{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({count:5,difficulty:2})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Unable to start generation");setJob(data.job_id);setMessage(data.cached?"Cached draft questions are ready.":"Generation queued. This page polls for completion.");if(!data.cached){const poll=async()=>{const state=await api.competency.job(data.job_id);if(state.status==="done")setMessage("Draft questions are ready for review in the question bank.");else if(state.status==="failed")setMessage(state.error||"Generation failed.");else window.setTimeout(poll,2000);};poll();}}catch(err){setMessage(err instanceof Error?err.message:"Unable to generate questions.");}finally{setBusy(false)}};
  return <div className="max-w-2xl space-y-5"><div><h1 className="text-2xl font-bold text-navy-900">Generate draft MCQs</h1><p className="text-sm text-slate-600">Create editable draft questions from one of your uploaded PDF resources.</p></div><form onSubmit={generate} className="space-y-3 rounded-xl border bg-white p-5"><label className="block text-sm font-medium" htmlFor="resource">PDF resource ID</label><input id="resource" required value={resourceId} onChange={e=>setResourceId(e.target.value)} className="w-full rounded-lg border p-2" placeholder="Resource UUID"/><button disabled={busy} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy?"Queueing…":"Generate 5 questions"}</button></form>{message&&<p className="rounded-lg bg-slate-100 p-3 text-sm">{message}{job&&` Job: ${job}`}</p>}</div>;
}
