"use client";

import { useEffect, useState } from "react";
import { api, CompetencyRecommendation, SkillGap, SkillNode } from "@/lib/api";
import { useAuth } from "@/components/layout/AppShell";

const pct = (n: number) => `${Math.round(Number(n) * 100)}%`;

export default function CompetencyPage() {
  const { user } = useAuth();
  const [skills, setSkills] = useState<SkillNode[]>([]); const [selected, setSelected] = useState<number>();
  const [trainers, setTrainers] = useState<CompetencyRecommendation[]>([]); const [gaps, setGaps] = useState<SkillGap[]>([]);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  useEffect(() => { if (user?.role !== "admin") return; Promise.all([api.profile.getSkillsTree(), api.competency.gaps()]).then(([tree, gapData]) => { const leaves = tree.flatMap(x => x.children || [x]); setSkills(leaves); setGaps(gapData.items); setSelected(leaves[0]?.id); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [user]);
  useEffect(() => { if (!selected) return; api.competency.trainers(selected).then(x => setTrainers(x.items)).catch(e => setError(e.message)); }, [selected]);
  if (user && user.role !== "admin") return <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">This page is available to administrators only.</p>;
  const refresh = async () => { try { const { job_id } = await api.competency.refresh(); setNotice("Recalculation has been queued."); const tick = async () => { const job = await api.competency.job(job_id); if (job.status === "done") { setNotice("Competency scores refreshed."); if (selected) setTrainers((await api.competency.trainers(selected)).items); } else if (job.status === "failed") setError(job.error || "Refresh failed."); else window.setTimeout(tick, 2000); }; tick(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to recalculate."); } };
  return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold text-navy-900">Competency Mapping</h1><p className="text-sm text-slate-600">Explainable, SQL-based trainer recommendations and workforce gaps.</p></div><button onClick={refresh} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Recalculate</button></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice && <p className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}<section className="rounded-xl border bg-white p-5"><label className="block text-sm font-semibold">Subject</label><select value={selected || ""} onChange={e => setSelected(Number(e.target.value))} className="mt-2 w-full rounded-lg border p-2"><option value="">Choose a subject</option>{skills.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="mt-5 grid gap-3 md:grid-cols-2">{loading ? <p>Loading data…</p> : trainers.length ? trainers.map(t => <article key={t.trainer_id} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><h2 className="font-semibold">#{t.rank_in_skill} {t.full_name}</h2><strong className="text-primary">{pct(t.total_score)}</strong></div><p className="mt-1 text-sm text-slate-600">{t.department || "IMD"}</p><div className="mt-3 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full bg-primary" style={{width:pct(t.total_score)}} /></div><p className="mt-3 text-xs text-slate-600">Skill match {pct(t.skill_match)} · pass rate {pct(t.pass_rate)} · rating {pct(t.rating_score)}</p><p className="mt-2 text-xs text-slate-500">Evidence: taught {t.courses_taught} courses, uploaded {t.resources_uploaded} resources, {t.attempts_count} learner attempts.</p></article>) : <p className="text-sm text-slate-600">No trainer evidence is available for this subject.</p>}</div></section><section><h2 className="text-lg font-bold">Skill gaps</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{gaps.map(g => <article key={g.skill_id} className="rounded-lg border bg-white p-4"><div className="flex justify-between"><h3 className="font-semibold">{g.skill}</h3><span className={`text-xs font-semibold ${g.gap_status === "critical gap" ? "text-red-700" : g.gap_status === "weak coverage" ? "text-amber-700" : "text-green-700"}`}>{g.gap_status}</span></div><p className="mt-2 text-sm text-slate-600">Demand: {g.demand} · Strong trainers: {g.strong_trainers}</p></article>)}</div></section></div>;
}
